{% set name = "rustywind" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/avencera/rustywind/archive/v{{ version }}.tar.gz
  sha256: d7ba13370721df4cc6728ca6b956f9a92ab260de08c03ef445a105a87e382546

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - rustywind --help

about:
  home: https://github.com/avencera/rustywind
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI for organizing Tailwind CSS classes
  dev_url: https://github.com/avencera/rustywind

extra:
  recipe-maintainers:
    - danielnachun
