context:
  version: "0.25.0"

package:
  name: rustywind
  version: ${{ version }}

source:
  url: https://github.com/avencera/rustywind/archive/v${{ version }}.tar.gz
  sha256: 32d3bff8de2b08a17fca485994e69e33619a78b1e397d4059dc445f62d19603b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rustywind --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI for organizing Tailwind CSS classes
  homepage: https://github.com/avencera/rustywind
  repository: https://github.com/avencera/rustywind

extra:
  recipe-maintainers:
    - danielnachun
