context:
  version: "0.24.3"

package:
  name: rustywind
  version: ${{ version }}

source:
  url: https://github.com/avencera/rustywind/archive/v${{ version }}.tar.gz
  sha256: 50706558f411722631db2449f5f05463703ebeffdea41f6e5f28f383992d06cb

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rustywind --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI for organizing Tailwind CSS classes
  homepage: https://github.com/avencera/rustywind
  repository: https://github.com/avencera/rustywind

extra:
  recipe-maintainers:
    - danielnachun
