context:
  version: "0.24.1"

package:
  name: rustywind
  version: ${{ version }}

source:
  url: https://github.com/avencera/rustywind/archive/v${{ version }}.tar.gz
  sha256: 06b154fc500f5f57bbabe1bbbc70c4b932fe5f5d49df5283591869c3fdfcc194

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rustywind --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI for organizing Tailwind CSS classes
  homepage: https://github.com/avencera/rustywind
  repository: https://github.com/avencera/rustywind

extra:
  recipe-maintainers:
    - danielnachun
